version: 2
updates:
    # Updates for Github Actions used in the repo
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
    # Updates for Gradle dependencies used in the app
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "weekly"
        ignore:
            -   dependency-name: ch.qos.logback:logback-classic
                versions: ">= 1.3.0"
            -   dependency-name: org.slf4j:slf4j-api
                versions: ">= 1.8.0"
