// release to central
apply plugin: 'maven-publish'
apply plugin: 'signing'
publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version
            from components.java

            pom {
                name = project.name
                description = project.description
                url = 'https://github.com/bratkartoffel/libtotp-java'

                scm {
                    connection = 'scm:git:https://github.com/bratkartoffel/libtotp-java.git'
                    developerConnection = 'scm:git:git@github.com:bratkartoffel/libtotp-java.git'
                    url = 'https://github.com/bratkartoffel/libtotp-java.git'
                }

                licenses {
                    license {
                        name = 'The MIT License (MIT)'
                        url = 'https://opensource.org/licenses/MIT'
                        distribution = 'repo'
                    }
                }

                developers {
                    developer {
                        id = 'bratkartoffel'
                        name = 'Simon Frankenberger'
                        email = 'simon-ossrh-release@fraho.eu'
                    }
                }
            }
        }
    }
    repositories {
        maven {
            credentials {
                username = project.hasProperty('ossrhUsername') ? project.property('ossrhUsername') : null
                password = project.hasProperty('ossrhPassword') ? project.property('ossrhPassword') : null
            }
            url = 'https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/'
        }
    }
}
